package com.ngxbot.common.model;
public enum EventType {
    TRADE_SIGNAL, STOP_LOSS_TRIGGERED, CIRCUIT_BREAKER_ACTIVATED,
    TRADE_EXECUTED, KILL_SWITCH_TOGGLED, DAILY_SUMMARY,
    WEEKLY_REPORT, SYSTEM_ERROR, OTP_REQUEST, APPROVAL_REQUEST,
    APPROVAL_RESPONSE
}
