package com.ngxbot.common.model;

public enum EventType {
    // Trading events
    TRADE_SIGNAL, STOP_LOSS_TRIGGERED, CIRCUIT_BREAKER_ACTIVATED,
    TRADE_EXECUTED, KILL_SWITCH_TOGGLED, DAILY_SUMMARY,
    WEEKLY_REPORT, SYSTEM_ERROR, OTP_REQUEST, APPROVAL_REQUEST,
    APPROVAL_RESPONSE,

    // News / corporate action events
    EARNINGS_RELEASE, DIVIDEND_ANNOUNCEMENT, RIGHTS_ISSUE,
    STOCK_SPLIT, BONUS_ISSUE, ACQUISITION_MERGER,
    REGULATORY_ACTION, MANAGEMENT_CHANGE, INSIDER_TRADE,
    CREDIT_RATING_CHANGE, SECTOR_NEWS, CBN_POLICY,
    TRADING_SUSPENSION, DELISTING_NOTICE, AGM_EGM_NOTICE,
    SHARE_BUYBACK
}
